# Generated by Django 5.2.8 on 2025-11-30 09:58

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0008_withdraw_state_removed'),
        ('placements', '0001_initial'),
        ('students', '0002_studentprofile_backlog_ledger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterializedViewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sql_definition', models.TextField(help_text='SQL for creating the materialized view')),
                ('refresh_strategy', models.CharField(choices=[('MANUAL', 'Manual Refresh'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('ON_DEMAND', 'On Demand (Triggered)')], default='DAILY', max_length=20)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materialized View Config',
                'verbose_name_plural': 'Materialized View Configs',
                'ordering': ['view_name'],
            },
        ),
        migrations.CreateModel(
            name='PlacementPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(default=dict, help_text="Policy conditions: {'offer_tier': 'DREAM', 'action': 'BLOCK_SIMILAR_TIER'}")),
                ('action', models.CharField(choices=[('ALLOW', 'Allow'), ('BLOCK', 'Block'), ('WITHDRAW_PENDING', 'Withdraw Pending Applications'), ('REQUIRE_APPROVAL', 'Require Admin Approval')], default='ALLOW', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority policies are evaluated first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placement Policy',
                'verbose_name_plural': 'Placement Policies',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('cache_data', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Cache',
                'verbose_name_plural': 'Dashboard Caches',
                'indexes': [models.Index(fields=['cache_key', 'expires_at'], name='analytics_d_cache_k_638a1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Semester GPA', max_digits=4, null=True)),
                ('total_credits', models.IntegerField(default=0)),
                ('earned_credits', models.IntegerField(default=0)),
                ('backlog_count', models.IntegerField(default=0)),
                ('academic_year', models.CharField(help_text='e.g., 2023-24', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
                'ordering': ['student', 'semester'],
                'indexes': [models.Index(fields=['student', 'semester'], name='analytics_a_student_19a419_idx')],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='BacklogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(help_text='Semester when backlog occurred')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=255)),
                ('fail_date', models.DateField(help_text='Date when subject was failed')),
                ('clear_date', models.DateField(blank=True, help_text='Date when backlog was cleared. Null if still active.', null=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_history', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Backlog History',
                'verbose_name_plural': 'Backlog Histories',
                'ordering': ['student', 'semester', 'fail_date'],
                'indexes': [models.Index(fields=['student', 'semester'], name='analytics_b_student_db88b0_idx'), models.Index(fields=['is_cleared'], name='analytics_b_is_clea_5dbc52_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TENTH_MARKSHEET', '10th Marksheet'), ('TWELFTH_MARKSHEET', '12th Marksheet'), ('SEMESTER_GRADE_CARD', 'Semester Grade Card'), ('OFFER_LETTER', 'Offer Letter'), ('HIGHER_STUDIES_ADMISSION', 'Higher Studies Admission Letter'), ('ENTREPRENEURSHIP_PROOF', 'Entrepreneurship Certificate')], max_length=50)),
                ('document_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_VERIFIED', 'Auto-Verified'), ('MANUAL_REVIEW', 'Needs Manual Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to='students.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
                'ordering': ['-verified_at', '-created_at'],
                'indexes': [models.Index(fields=['student', 'verification_status'], name='analytics_d_student_7c5057_idx')],
                'unique_together': {('student', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='PlacementOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed component of CTC (LPA)', max_digits=10, null=True)),
                ('salary_variable', models.DecimalField(blank=True, decimal_places=2, help_text='Variable component of CTC (LPA)', max_digits=10, null=True)),
                ('salary_bonus', models.DecimalField(blank=True, decimal_places=2, help_text='Signing/Joining bonus (LPA)', max_digits=10, null=True)),
                ('total_ctc', models.DecimalField(decimal_places=2, help_text='Total Cost to Company (LPA) - for NIRF median calculation', max_digits=10)),
                ('offer_tier', models.CharField(choices=[('STANDARD', 'Standard'), ('DREAM', 'Dream'), ('SUPER_DREAM', 'Super Dream')], default='STANDARD', help_text='Offer tier for placement policy enforcement', max_length=20)),
                ('offer_date', models.DateField()),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('offer_letter', cloudinary.models.CloudinaryField(blank=True, help_text='Uploaded offer letter for NAAC compliance', max_length=255, null=True, verbose_name='raw')),
                ('offer_letter_url', models.URLField(blank=True, help_text='Secure signed URL for offer letter (NAAC evidence link)', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='TPO verification status (required for NAAC)')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_type', models.CharField(choices=[('PLACEMENT', 'Placement'), ('HIGHER_STUDIES', 'Higher Studies'), ('ENTREPRENEURSHIP', 'Entrepreneurship')], default='PLACEMENT', help_text='NBA requires equal weight to Placement, Higher Studies, Entrepreneurship', max_length=20)),
                ('higher_studies_proof', cloudinary.models.CloudinaryField(blank=True, help_text='Admission letter for higher studies (NBA evidence)', max_length=255, null=True, verbose_name='raw')),
                ('entrepreneurship_proof', cloudinary.models.CloudinaryField(blank=True, help_text='GST Registration or Startup Certificate (NBA evidence)', max_length=255, null=True, verbose_name='raw')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_offer', to='applications.companydriveapplication')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_offers', to='placements.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_offers', to='students.studentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Offer',
                'verbose_name_plural': 'Placement Offers',
                'ordering': ['-offer_date'],
                'indexes': [models.Index(fields=['student', 'offer_date'], name='analytics_p_student_06a469_idx'), models.Index(fields=['is_verified'], name='analytics_p_is_veri_a52e1d_idx'), models.Index(fields=['outcome_type'], name='analytics_p_outcome_0ac16a_idx'), models.Index(fields=['total_ctc'], name='analytics_p_total_c_871b51_idx')],
            },
        ),
    ]
