# Generated by Django 5.2.8 on 2025-11-17 18:52

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_type', models.CharField(choices=[('FullTime', 'FullTime'), ('Internship', 'Internship'), ('Contract', 'Contract')], max_length=20)),
                ('job_mode', models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('rounds', models.JSONField(blank=True, null=True)),
                ('locations', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multiple_allowed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='companies.company')),
                ('placement_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_drives', to='placements.placementdrive')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description_ug', models.TextField(blank=True, null=True)),
                ('description_pg', models.TextField(blank=True, null=True)),
                ('job_pdf', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('job_desc', models.JSONField(blank=True, null=True)),
                ('min_ug_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_pg_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_active_backlogs', models.IntegerField(blank=True, null=True)),
                ('ug_package_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ug_package_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pg_package_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pg_package_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ug_stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pg_stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='placements.companydrive')),
            ],
        ),
        migrations.CreateModel(
            name='JobProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.job')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
            options={
                'unique_together': {('job', 'program')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='eligible_programs',
            field=models.ManyToManyField(blank=True, through='placements.JobProgram', to='core.program'),
        ),
    ]
