# Generated by Django 5.2.6 on 2025-09-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydrive',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_drives', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companydrive',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_drives', to='placements.placementdrive'),
        ),
        migrations.AlterUniqueTogether(
            name='companydrive',
            unique_together={('drive', 'company')},
        ),
    ]
