# Generated by Django 5.2.6 on 2025-10-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('placements', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description_ug', models.TextField(blank=True, null=True)),
                ('description_pg', models.TextField(blank=True, null=True)),
                ('job_pdf_url', models.URLField(blank=True, max_length=255, null=True)),
                ('min_ug_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_pg_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_active_backlogs', models.IntegerField(blank=True, null=True)),
                ('ug_package_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ug_package_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pg_package_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pg_package_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ug_stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pg_stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='placements.companydrive')),
            ],
        ),
        migrations.CreateModel(
            name='JobProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
            options={
                'unique_together': {('job', 'program')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='eligible_programs',
            field=models.ManyToManyField(blank=True, through='jobs.JobProgram', to='core.program'),
        ),
    ]
