# Generated by Django 5.2.6 on 2025-09-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='placements.companydrive'),
        ),
        migrations.AddField(
            model_name='jobprogram',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program'),
        ),
        migrations.AddField(
            model_name='job',
            name='eligible_programs',
            field=models.ManyToManyField(blank=True, through='jobs.JobProgram', to='core.program'),
        ),
        migrations.AlterUniqueTogether(
            name='jobprogram',
            unique_together={('job', 'program')},
        ),
    ]
