# Generated by Django 5.2.8 on 2025-11-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('placements', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydriveapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='drive_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to='applications.companydriveapplication'),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.job'),
        ),
        migrations.AlterUniqueTogether(
            name='companydriveapplication',
            unique_together={('company_drive', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='jobpreference',
            unique_together={('drive_application', 'job'), ('drive_application', 'preference_order')},
        ),
    ]
