# Generated by Django 5.2.8 on 2025-11-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='backlog_ledger',
            field=models.JSONField(blank=True, default=dict, help_text='Transactional record: {semester: {subject: {fail_date, clear_date}}}'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='domicile_state',
            field=models.CharField(blank=True, help_text='State of domicile for NIRF diversity reporting', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='entry_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Entry'), ('LATERAL', 'Lateral Entry'), ('TRANSFER', 'Transfer')], default='REGULAR', help_text='Critical for NBA Success Index calculation', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONTIME_NO_BACKLOG', 'Graduated On Time Without Backlogs'), ('ONTIME_WITH_BACKLOG', 'Graduated On Time With Cleared Backlogs'), ('DELAYED', 'Graduated With Delay'), ('NOT_GRADUATED', 'Not Graduated')], default='PENDING', help_text='NBA graduation status tracking', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='social_category',
            field=models.CharField(blank=True, choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('EWS', 'Economically Weaker Section')], help_text='Social category for NIRF diversity reporting', max_length=10, null=True),
        ),
    ]
