name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13" 

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage pytest-django 

    - name: Run Tests with Coverage
      run: |
        export SECRET_KEY=a-dummy-secret-key-for-ci
        
        coverage run -m pytest
        
        # Report coverage
        coverage report --fail-under=85 